---
version: '3'
services:
  example:
    build:
      context: .
    depends_on:
      - postgres_c
    ports:
      - "9080:8080"
  postgres_c:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
