---
version: '3'
services:
  example:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
